[build-system]
requires = ["setuptools>=61.0", "wheel", "pybind11", "coal>=3.0.2", "eigenpy>=3.12.0", "cmeel-eigen", "cmeel-libomp"]
build-backend = "setuptools.build_meta"

[project]
name = "diffcollision"
version = "0.1.0"
description = "Robust Differentiable Collision Detection for General Objects."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "CC BY-NC 4.0" }
authors = [{ name = "Jiayi Chen" }]
keywords = ["collision", "differentiable", "robotics", "physics"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Other/Proprietary License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
]

dependencies = [
    "coal>=3.0.2",
    "cmeel-eigen",
    "cmeel-libomp",
    "dacite>=1.9.2",
    "pyyaml",
    "torch==2.4.0",
    "trimesh[easy]>=4.11.5",
    "tyro>=0.9.0",
    "warp-lang>=1.12.1",
    "loguru>=0.7.3",
]

[project.optional-dependencies]
examples = [
    "pytorch-kinematics",
    "mujoco",
    "usd-core"
]
test = [
    "pytest>=8.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]
